### ISSUE TITLE
Not working with JSX

### ISSUE THREAD

**Issue by kethan** [theSherwood/sinuous-context#3]
The context doesn't work with JSX?

**Comment by theSherwood** [comment]
Hmm. Doesn't seem to work for JSX at present. Thanks for bringing this to my attention.

**Comment by theSherwood** [comment]
@kethan Okay. It does seem to work in [this sandbox](https://codesandbox.io/s/sinuous-jsx-context-4ze78), but there are two gotchas:

1. The `Context` component has to be wrapped in another element. This is because calling the `Context` function returns an `update` function. So the `Context` function/component must be wrapped in another call to `h` so that the `update` function (which returns the dom nodes) can be called.

2. There seems to be a mismatch between the `sinuous` `h` and the `h` used by `sinuous-context`. Pull the `h` of `api` to use it. 

I'll dig into these two things and see if I can find a solution. Hopefully this helps in the meantime.

**Comment by kethan** [comment]
Not working on my code. https://codesandbox.io/s/sinuous-playground-jsx-ym50k?file=/index.js

**Comment by theSherwood** [comment]
Give version `0.3.1` a try. It ought to work better with jsx. Keep in mind, the `Context` component cannot be the root. Wrap it in a div or something.

**Comment by kethan** [comment]
> Give version `0.3.1` a try. It ought to work better with jsx. Keep in mind, the `Context` component cannot be the root. Wrap it in a div or something.

using latest one... wrapped in div..still not working..

**Comment by theSherwood** [comment]
Okay. If you have a simple example with a clear bug and the expected behavior outlined, I'll take a look.

**Comment by kethan** [comment]
> Okay. If you have a simple example with a clear bug and the expected behavior outlined, I'll take a look.

can you check now? https://codesandbox.io/s/sinuous-playground-jsx-ceu37?file=/index.js

**Comment by theSherwood** [comment]
Thanks! That helps a lot. I got it working by using a different babel configuration. [Sandbox](https://codesandbox.io/s/sinuous-jsx-context-pligc?file=/src/index.js)

Would the kind of babel configuration that's in that sandbox work for you or is there some specific config that you need? I confess I don't know much about babel.

**Comment by kethan** [comment]
> Thanks! That helps a lot. I got it working by using a different babel configuration. [Sandbox](https://codesandbox.io/s/sinuous-jsx-context-pligc?file=/src/index.js)
> 
> Would the kind of babel configuration that's in that sandbox work for you or is there some specific config that you need? I confess I don't know much about babel.

Yeah need to update the config.
